name: Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: "tests on python ${{ matrix.python-version }} (optional: ${{ matrix.experimental }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7]
        experimental: [false]

        include:
          - python-version: 3.6
            experimental: true
          - python-version: 3.7
            experimental: true
          - python-version: 3.8
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install os dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -yq \
            libogg-dev \
            libportmidi-dev \
            libsdl-image1.2-dev \
            libsdl-mixer1.2-dev \
            libsdl-ttf2.0-dev \
            libsdl1.2-dev \
            libsoundtouch-dev \
            libswscale-dev \
            libtheora-dev \
            libvorbis-dev \
            mesa-utils \
            portaudio19-dev
          sudo apt-get install -y gcc g++

      - name: Install python dependencies
        run: |
          pip install pytest pytest-cov
          pip install -r requirements.txt

      - name: "Run tests (optional: ${{ matrix.experimental }})"
        continue-on-error: ${{ matrix.experimental }}
        uses: GabrielBB/xvfb-action@v1
        with:
          run: pytest fofix
        env:
          SDL_AUDIODRIVER: dummy

  gitlint:
    name: gitlint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install gitlint
        run: pip install "gitlint==0.15.1"

      - name: Run gitlint
        run: gitlint --commits origin..HEAD
        continue-on-error: true
